#!/usr/bin/env bash
# Populate apps/desktop/src-tauri/binaries/ with the sidecars Tauri expects.
#
# Tauri's externalBin resolves "binaries/adib-engine" to
# "binaries/adib-engine-<target-triple>", so every artifact gets that suffix.
#
#   ./scripts/prepare-binaries.sh          # dev: engine wrapper delegating to uv
#   ./scripts/prepare-binaries.sh --release # frozen engine via PyInstaller
#
# Either mode also fetches the Typst binary, which the engine shells out to when
# rendering PDFs.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="$ROOT/apps/desktop/src-tauri/binaries"
MODE="dev"
[[ "${1:-}" == "--release" ]] && MODE="release"

TRIPLE="$(rustc -vV | awk '/^host:/ {print $2}')"
mkdir -p "$BIN_DIR"

echo "==> target triple: $TRIPLE (mode: $MODE)"

# --- engine ------------------------------------------------------------------
ENGINE_OUT="$BIN_DIR/adib-engine-$TRIPLE"

if [[ "$MODE" == "release" ]]; then
  echo "==> freezing engine with PyInstaller"
  (cd "$ROOT/engine" && uv run pyinstaller --clean --noconfirm adib-engine.spec)
  cp "$ROOT/engine/dist/adib-engine/adib-engine" "$ENGINE_OUT"
else
  echo "==> writing dev engine wrapper -> $ENGINE_OUT"
  # A wrapper rather than a frozen binary keeps `npm run tauri dev` on the same
  # code path as production (spawn a sidecar, read the ready line) while still
  # picking up Python edits without a rebuild.
  cat > "$ENGINE_OUT" <<EOF
#!/usr/bin/env bash
# Generated by scripts/prepare-binaries.sh -- do not edit, do not commit.
exec uv run --project "$ROOT/engine" adib-engine "\$@"
EOF
fi
chmod +x "$ENGINE_OUT"

# --- typst -------------------------------------------------------------------
TYPST_OUT="$BIN_DIR/typst-$TRIPLE"

if [[ -x "$TYPST_OUT" ]]; then
  echo "==> typst already present, skipping download"
else
  case "$TRIPLE" in
    aarch64-apple-darwin)      TYPST_ASSET="typst-aarch64-apple-darwin.tar.xz" ;;
    x86_64-apple-darwin)       TYPST_ASSET="typst-x86_64-apple-darwin.tar.xz" ;;
    x86_64-unknown-linux-gnu)  TYPST_ASSET="typst-x86_64-unknown-linux-musl.tar.xz" ;;
    aarch64-unknown-linux-gnu) TYPST_ASSET="typst-aarch64-unknown-linux-musl.tar.xz" ;;
    x86_64-pc-windows-msvc)    TYPST_ASSET="typst-x86_64-pc-windows-msvc.zip" ;;
    *) echo "unsupported target triple for typst: $TRIPLE" >&2; exit 1 ;;
  esac

  TYPST_VERSION="${TYPST_VERSION:-$(curl -fsSL https://api.github.com/repos/typst/typst/releases/latest \
    | sed -n 's/.*"tag_name": *"v\([^"]*\)".*/\1/p' | head -1)}"
  [[ -n "$TYPST_VERSION" ]] || { echo "could not resolve latest typst version" >&2; exit 1; }

  echo "==> downloading typst v$TYPST_VERSION ($TYPST_ASSET)"
  TMP="$(mktemp -d)"
  trap 'rm -rf "$TMP"' EXIT
  curl -fsSL -o "$TMP/$TYPST_ASSET" \
    "https://github.com/typst/typst/releases/download/v$TYPST_VERSION/$TYPST_ASSET"

  if [[ "$TYPST_ASSET" == *.zip ]]; then
    unzip -q "$TMP/$TYPST_ASSET" -d "$TMP"
  else
    tar -xJf "$TMP/$TYPST_ASSET" -C "$TMP"
  fi
  cp "$(find "$TMP" -type f -name 'typst' -o -type f -name 'typst.exe' | head -1)" "$TYPST_OUT"
  chmod +x "$TYPST_OUT"
fi

echo "==> done:"
ls -l "$BIN_DIR"
